### PR TITLE
Feature: Syntax Highlight Klipper Configuration

### PR DESCRIPTION
**Pull request by pfemiani**
I originally crated a PR to get this in to the old repo, this was before it was transitions to its new owner, i can't give up the syntax highlighting 🤣 so this is the only reason i haven't switched/updated to the new plugin source, so let's try this PR again 🤪 ...

I made an attempt at implementing syntax highlighting of the Klipper config. It does syntax highlighting and editing via the ACE editor (https://github.com/ajaxorg/ace). Makes is so much easier/nicer to navigate and work with the Klipper config file (printer.cfg).

Screen Shot 2020-08-08 at 11 48 29 AM

### CODE REVIEW

**Comment by thelastWallE** [comment]
Hi. I integrated your old PR into my own branch where all other commits are merged in.
It's on https://github.com/thelastWallE/OctoprintKlipperPlugin/tree/testingnewversion
Seems like i need to get your new PR updated in my branch now. :)

**Comment by pfemiani** [comment]
@thelastWallE I haven't made any changes that I can think of since the original pull request, so hopefully its pretty straight forward. Please let me know if there is anything I can do to help out?

**Comment by thelastWallE** [comment]
ah it is the old PR. ok then this should be the same changes i got. 
you can maybe try my branch and see if this works for you.
i just shove the internal css to the external file and did some work on the whole layout of the klippertab because where there some scrollbars if the rendersize was not 100%.

**Comment by thelastWallE** [comment]
Merged/Modified into 0.3.4rc1

**Pull request closed without merging**
